### ISSUE TITLE
Symphony 4 only?

### ISSUE THREAD

**Issue by animaux** [fhamon/ctrl_k#2]
Hi, this sounds nice, but apart from inside usage at deuxhuithuit Symphony 4 is not spread very wide yet. Any chance to get this running in `2.7.x`? Or does it rely too much on v4?

**Comment by fhamon** [comment]
Hey @animaux !

On a technical level, the extension can run on `2.7.x` without any issues since I only use `/ajax/sections/` data to do the magic 😁. I released it under `4.0` only beacause of the new design language that Symphony 4 will have. Feel free to test it on your end, but I don't think I will port it to previous version for now.

Cheers !

**Comment by animaux** [comment]
Thanks for your reply! I did try it in `2.7.7`, but it came up with a JS-error: 

    TypeError: undefined is not an object (evaluating 'element.name.toLowerCase')

**Comment by fhamon** [comment]
Fixed it ! I tested it in a 2.7 install I have and it works! It's weird looking, but it works haha 😁 

https://github.com/fhamon/ctrl_k/releases/tag/1.0.1

**Comment by animaux** [comment]
Brilliant, thanks! `;)`
